[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
{% if async -%}
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
{% endif -%}
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
