name: Validate templates

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  rust-templates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - uses: taiki-e/install-action@v2
        with:
          tool: just,cargo-generate@0.23.14
      - run: just verify
